name: Deploy NGINX App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: engineerd/setup-kind@v0.6.2
        with:
          version: "v0.24.0"

      - run: kind create cluster --name ci-nginx

      - run: echo "KUBECONFIG=$(kind get kubeconfig-path --name=ci-nginx)" >> $GITHUB_ENV

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - run: terraform init
        working-directory: terraform

      - run: terraform apply -auto-approve
        working-directory: terraform

      - run: kubectl rollout status deployment/nginx-app -n nginx-app --timeout=120s

      - run: |
          kubectl port-forward svc/nginx-app -n nginx-app 8080:80 &
          sleep 10
          curl --fail http://localhost:8080

      - if: always()
        run: terraform destroy -auto-approve
        working-directory: terraform

      - if: always()
        run: kind delete cluster --name ci-nginx
