name: Deploy NGINX App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install kind
        uses: engineerd/setup-kind@v0.6.1
      - name: Create kind cluster
        run: kind create cluster --name ci-nginx
      - name: Set kubeconfig
        run: echo "KUBECONFIG=$(kind get kubeconfig-path --name=ci-nginx)" >> $GITHUB_ENV
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0
      - name: Terraform Init
        working-directory: terraform
        run: terraform init
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
      - name: Wait for deployment
        run: |
          kubectl rollout status deployment/nginx-app -n nginx-app --timeout=120s
      - name: Port-forward & curl
        run: |
          kubectl port-forward svc/nginx-app -n nginx-app 8080:80 &
          sleep 10
          curl --fail http://localhost:8080
      - name: Terraform Destroy
        if: always()
        working-directory: terraform
        run: terraform destroy -auto-approve
      - name: Delete kind cluster
        if: always()
        run: kind delete cluster --name ci-nginx
